if (Test-Path -Path "C:\SEGA\system\new.sgxsegaboot.exe") {
    Write-Host "Update appboot..."
    Move-Item -Force -Path "C:\SEGA\system\new.sgxsegaboot.exe" -Destination "C:\SEGA\system\sgxsegaboot.exe"
    Start-Process -FilePath uwfmgr.exe -Verb runas -WindowStyle Hidden -Wait -ArgumentList "file commit C:\SEGA\system\sgxsegaboot.exe"
    Start-Process -FilePath uwfmgr.exe -Verb runas -WindowStyle Hidden -Wait -ArgumentList "file commit-delete C:\SEGA\system\new.sgxsegaboot.exe"
}

Start-Process -FilePath "C:\SEGA\system\sgxsegaboot.exe" -Verb runas
exit
# SIG # Begin signature block
# MIIGEgYJKoZIhvcNAQcCoIIGAzCCBf8CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUTcrEZDrGKPzY8JwbdGBenaLC
# MwGgggOCMIIDfjCCAmagAwIBAgIQJlq0EDKWmKtOwveGVRLWsTANBgkqhkiG9w0B
# AQUFADBFMUMwQQYDVQQDDDpDb2RlIFNpZ25pbmcgLSBBY2FkZW15IENpdHkgUmVz
# ZWFyY2ggUC5TLlIuIChmb3IgTWlzc2xlc3MpMB4XDTIzMTIyOTIzMTMzNVoXDTMw
# MTIyNDA1MDAwMFowRTFDMEEGA1UEAww6Q29kZSBTaWduaW5nIC0gQWNhZGVteSBD
# aXR5IFJlc2VhcmNoIFAuUy5SLiAoZm9yIE1pc3NsZXNzKTCCASIwDQYJKoZIhvcN
# AQEBBQADggEPADCCAQoCggEBANqtipcPEhVWQAUz+KVOBm806ZX0LVp/DV/AW2yJ
# VlBcmT4WP8cIEIay4jU3QZCoVYztQnxI6VUgXsxrpgVfdmWv7Mi1T0yESaicB56k
# c+E+SuJ5QPJiNEOom1cFhpriafjIwjcXazBP1RfqzqP7yfEbN3CxSp4jpRHCfIbq
# agYyVjDqMnyk4iXh2oOY19OHCmHqKCZ0jRlDLpU2RCVMEV0pNewq7O2wn745NxF2
# cm4FP4CU48Zav2LJDwlI2ZA0j5xVJKnwLhRhde0A+N6oFG5GWP709lW9A2EY4tIV
# GKX+FH6BwnXCAedWoiHMa55m0u1KGfxUJc1wC6fnFzEa5mECAwEAAaNqMGgwDgYD
# VR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMCIGA1UdEQQbMBmCF2Js
# dWUtc3RlZWwubWlzc2xlc3MubmV0MB0GA1UdDgQWBBSQo+sgAwlIIYWIsEVsvXgF
# dUTz0DANBgkqhkiG9w0BAQUFAAOCAQEAC8jrcbhyQLn2ddfFn2cRk4ONXdp7EDbE
# Eqr+OifivDuUwK5hV2ds9ygbvcuYK2hv1wrixTVElIvQ40qXzSPtbSwlQ86OCGWc
# hrnnI04iAMKFq8m3rxVrePe0rGwJk/NcIXORRQbU8H3yI2UEMAOqCXr8CGcJyxer
# n9jLCxIBQXf8nJ9GU7GydDn/ODFdqCKUhbPAlMCQC4kdQMLPc+6XYnlQ6ex2qSPq
# MT5Josy660b+bUb+PrvhOEG5TH2MP+SCq9hQJZ3viv/ciG1c5x6WnW2HU6WM7XC1
# HKt1v5NZCaCwDD1n0v4RqIODI0Qk9eqmD+45rkrQdZHRZuhwgmBASTGCAfowggH2
# AgEBMFkwRTFDMEEGA1UEAww6Q29kZSBTaWduaW5nIC0gQWNhZGVteSBDaXR5IFJl
# c2VhcmNoIFAuUy5SLiAoZm9yIE1pc3NsZXNzKQIQJlq0EDKWmKtOwveGVRLWsTAJ
# BgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0B
# CQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAj
# BgkqhkiG9w0BCQQxFgQUWYfqvSZc9Roz1MrnNNbO8KbZIKcwDQYJKoZIhvcNAQEB
# BQAEggEACA2RFgxJKdE6DcPwTY5NMwQGG/cKD+dF7H9FDs/DVYIer/aS8QwMCeOJ
# QgKrgA0WSbZXU4NAeenEfmYrox+N5g3rzHvW7/uoL7C2zA+Ty5jB45vr4EWwlnFG
# MneDo43Wu4T3GbJl6uBy7qw88TyF50EfUQkVIdFlOPjWQKg4WTkESSS+36XdpssR
# dNFAw84XJUWCEeOn1h257SnPpFfaVc/WHjvJLmKV1vRDvt+YuTcqvx/g36fQbxg2
# x4AazU1mk1zOY2LfOzLvT9Ymi2tDCeEEHuLki6Oq0WSS8kFAtsT1KifUuWOm/AKR
# E+dkGlNgjUold16ONidfy686b+yfWQ==
# SIG # End signature block
